In [3]:
import numpy as np

In [26]:
n = 4
m = 5

In [27]:
x = np.arange(n)
y = np.arange(m)
x, y

(array([0, 1, 2, 3]), array([0, 1, 2, 3, 4]))

### Version in the book

In [28]:
rows, cols = np.meshgrid(x, y, indexing='ij')
rows  

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [29]:
cols

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [30]:
np.hypot(rows, cols)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ]])

### Using broadcasting

In [31]:
X = x[:, None]
Y = y[None, :]
X

array([[0],
       [1],
       [2],
       [3]])

In [32]:
Y

array([[0, 1, 2, 3, 4]])

In [33]:
X + Y

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [34]:
np.sqrt(X**2 + Y**2)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ]])

### Using outer product

In [35]:
np.hypot.outer(x, y)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ]])

In [36]:
def make_scape(n, m):
    x = np.arange(n)
    y = np.arange(m)
    return np.hypot.outer(x, y)

In [37]:
make_scape(4, 5)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ]])